# Generated by Django 3.2.9 on 2021-12-08 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campo',
            new_name='Disciplina',
        ),
        migrations.RenameField(
            model_name='atividade',
            old_name='campo',
            new_name='disciplina',
        ),
    ]
