# Generated by Django 3.2.9 on 2021-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0004_rename_local_livro_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='local',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Gênero'),
        ),
    ]
