# Generated by Django 3.2.9 on 2021-12-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0007_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='horario',
            field=models.TimeField(),
        ),
    ]
