# Generated by Django 3.2.9 on 2021-12-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastro', '0008_alter_computer_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='codigo',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código'),
        ),
    ]
